from django.db import transaction
from django.db.models import Sum
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from apps.accounts.permissions import IsAdmin, IsSelfStudentViaStudentFeeFK
from .models import FeeStructure, StudentFee, Payment
from .serializers import FeeStructureSerializer, StudentFeeSerializer, FeePaymentSerializer


class FeeStructureViewSet(viewsets.ModelViewSet):
    """The fee schedule per class/session. Master data -- Admin only."""
    queryset = FeeStructure.objects.all()
    serializer_class = FeeStructureSerializer
    filterset_fields = ['school_class', 'session', 'fee_type']
    permission_classes = [IsAdmin]


class _StudentFeeDetailPermission(IsAuthenticated):
    """Admin, or the owning Student, may retrieve a single StudentFee row."""

    def has_object_permission(self, request, view, obj):
        user = request.user
        if user.role == 'ADMIN':
            return True
        if user.role == 'STUDENT':
            return obj.student.user == user
        return False


class StudentFeeViewSet(viewsets.ModelViewSet):
    """
    Admin: full access (assign fees, view all students' totals/paid/remaining).
    Student: may only view their OWN fee record (total/paid/remaining +
        nested payment history). Cannot create/edit/delete.
    Teacher: no access -- financial records are Admin/Student only.
    """
    queryset = StudentFee.objects.select_related('student__user', 'fee_structure').all()
    serializer_class = StudentFeeSerializer
    filterset_fields = ['student', 'fee_structure']

    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user.role == 'STUDENT' and self.action == 'list':
            return qs.filter(student__user=user)
        if user.role == 'TEACHER':
            return qs.none()
        # retrieve/update/destroy: unfiltered -- object-level permission
        # decides access so a foreign ID returns 403, not 404.
        return qs

    def get_permissions(self):
        if self.action in ('create', 'update', 'partial_update', 'destroy', 'dashboard_summary'):
            return [IsAuthenticated(), IsAdmin()]
        if self.action == 'list':
            return [IsAuthenticated()]
        # retrieve
        return [_StudentFeeDetailPermission()]

    @action(detail=False, methods=['get'])
    def dashboard_summary(self, request):
        """Admin dashboard: total collected, total pending, across all students."""
        total_collected = Payment.objects.aggregate(t=Sum('amount'))['t'] or 0
        all_fees = StudentFee.objects.all()
        total_payable = sum(f.net_payable for f in all_fees)
        return Response({
            'total_fee_collection': float(total_collected),
            'total_payable': float(total_payable),
            'total_pending': float(total_payable) - float(total_collected),
        })


class PaymentViewSet(viewsets.ModelViewSet):
    """
    Records an individual fee payment. Only Admin can create/edit/delete.
    A student may view (list/retrieve) only their own payments/receipts.
    created_at (date + time) and created_by are always generated by the
    backend -- the client can never set or edit them.
    """
    queryset = Payment.objects.select_related('student_fee__student__user').all()
    serializer_class = FeePaymentSerializer
    filterset_fields = ['student_fee', 'method']

    def get_queryset(self):
        qs = super().get_queryset()
        user = self.request.user
        if user.role == 'ADMIN':
            return qs
        if user.role == 'STUDENT' and self.action == 'list':
            return qs.filter(student_fee__student__user=user)
        if user.role == 'STUDENT':
            return qs
        return qs.none()
    

    def get_permissions(self):
        if self.action in ('list', 'retrieve'):
            return [IsSelfStudentViaStudentFeeFK()]
        # create/update/partial_update/destroy: Admin only. We do not allow
        # editing a payment's timestamp; financial history is never
        # silently overwritten.
        return [IsAuthenticated(), IsAdmin()]

    @transaction.atomic
    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)
