from django.db import transaction
from rest_framework import serializers
from apps.accounts.serializers import UserSerializer
from apps.accounts.models import User
from .models import Teacher, TeacherDocument, TeacherSalary, SalaryPayment, TeacherAttendance


class TeacherDocumentSerializer(serializers.ModelSerializer):
    uploaded_by_name = serializers.CharField(source='uploaded_by.get_full_name', read_only=True)

    class Meta:
        model = TeacherDocument
        fields = '__all__'
        read_only_fields = ['uploaded_at', 'uploaded_by']


class SalaryPaymentSerializer(serializers.ModelSerializer):
    created_by_name = serializers.CharField(source='created_by.get_full_name', read_only=True)

    class Meta:
        model = SalaryPayment
        fields = '__all__'
        # created_at/created_by are generated by the backend only -- never
        # accepted from the client, and never editable after the fact.
        read_only_fields = ['created_at', 'created_by']

    def validate_amount(self, value):
        if value <= 0:
            raise serializers.ValidationError(
                'Salary payment must be greater than zero.'
            )
        return value

    def validate(self, attrs):
        teacher_salary = attrs.get('teacher_salary') or getattr(self.instance, 'teacher_salary', None)
        amount = attrs.get('amount')

        if teacher_salary and amount is not None:
            already_paid = sum(
                p.amount for p in teacher_salary.payments.exclude(pk=getattr(self.instance, 'pk', None))
            )
            if already_paid + amount > teacher_salary.amount:
                raise serializers.ValidationError(
                    'Payment would exceed the salary amount due for this month.'
                )

        return attrs


class TeacherSalarySerializer(serializers.ModelSerializer):
    teacher_name = serializers.CharField(source='teacher.user.get_full_name', read_only=True)
    employee_id = serializers.CharField(source='teacher.employee_id', read_only=True)
    payments = SalaryPaymentSerializer(many=True, read_only=True)
    paid_amount = serializers.SerializerMethodField()
    remaining_amount = serializers.SerializerMethodField()

    class Meta:
        model = TeacherSalary
        fields = '__all__'
        read_only_fields = ['created_at', 'updated_at', 'created_by']

    def get_paid_amount(self, obj):
        return obj.paid_amount

    def get_remaining_amount(self, obj):
        return obj.remaining_amount

    def validate(self, attrs):
        teacher = attrs.get('teacher') or getattr(self.instance, 'teacher', None)
        month = attrs.get('salary_month') or getattr(self.instance, 'salary_month', None)

        existing = TeacherSalary.objects.filter(teacher=teacher, salary_month=month)
        if self.instance:
            existing = existing.exclude(pk=self.instance.pk)
        if existing.exists():
            raise serializers.ValidationError(
                'A salary record for this teacher and month already exists.'
            )

        return attrs


class TeacherSerializer(serializers.ModelSerializer):
    user = UserSerializer(read_only=True)
    documents = TeacherDocumentSerializer(many=True, read_only=True)
    full_name = serializers.CharField(source='user.get_full_name', read_only=True)

    class Meta:
        model = Teacher
        fields = '__all__'


class TeacherPublicSerializer(serializers.ModelSerializer):
    """A version of the teacher record with no financial/private fields.

    Used anywhere a colleague's *non-sensitive* info needs to be shown (e.g.
    'Ms. Rao teaches Physics') without leaking salary or bank details.
    """
    user = UserSerializer(read_only=True)
    full_name = serializers.CharField(source='user.get_full_name', read_only=True)

    class Meta:
        model = Teacher
        fields = [
            'id', 'user', 'full_name', 'employee_id', 'department',
            'qualification', 'subjects', 'classes', 'joining_date',
        ]


class TeacherCreateSerializer(serializers.ModelSerializer):
    """Creates the User (role=TEACHER) and Teacher profile together."""
    username = serializers.CharField(write_only=True)
    email = serializers.EmailField(write_only=True)
    first_name = serializers.CharField(write_only=True)
    last_name = serializers.CharField(write_only=True)
    password = serializers.CharField(write_only=True, min_length=8)
    experience_years = serializers.IntegerField(required=False, default=0)

    class Meta:
        model = Teacher
        fields = [
            'id',
            'username', 'email', 'first_name', 'last_name', 'password',
            'employee_id', 'gender', 'date_of_birth', 'qualification',
            'experience_years', 'department', 'subjects', 'classes',
            'aadhaar_number', 'pan_number', 'bank_account_number', 'bank_ifsc',
            'bank_name', 'salary', 'joining_date', 'address',
        ]

    def validate_username(self, value):
        val = value.strip()
        if User.objects.filter(username__iexact=val).exists():
            raise serializers.ValidationError("A user with this username already exists.")
        return val

    def validate_email(self, value):
        val = value.strip().lower()
        if User.objects.filter(email__iexact=val).exists():
            raise serializers.ValidationError("A user with this email address already exists.")
        return val

    def to_internal_value(self, data):
        data = data.copy() if hasattr(data, 'copy') else dict(data)
        if 'experience_years' in data and (data['experience_years'] == '' or data['experience_years'] is None):
            data['experience_years'] = 0
        if 'salary' in data and (data['salary'] == '' or data['salary'] is None):
            data['salary'] = None
        return super().to_internal_value(data)

    @transaction.atomic
    def create(self, validated_data):
        subjects = validated_data.pop('subjects', [])
        classes = validated_data.pop('classes', [])
        username = validated_data.pop('username').strip()
        email = validated_data.pop('email').strip().lower()
        first_name = validated_data.pop('first_name').strip()
        last_name = validated_data.pop('last_name').strip()
        password = validated_data.pop('password')

        user = User.objects.create_user(
            username=username,
            email=email,
            first_name=first_name,
            last_name=last_name,
            password=password,
            role=User.Role.TEACHER,
        )
        teacher = Teacher.objects.create(user=user, **validated_data)
        if subjects:
            teacher.subjects.set(subjects)
        if classes:
            teacher.classes.set(classes)
        return teacher

    def to_representation(self, instance):
        return TeacherSerializer(instance, context=self.context).data


class TeacherAttendanceSerializer(serializers.ModelSerializer):
    teacher_name = serializers.CharField(source='teacher.user.get_full_name', read_only=True)
    employee_id = serializers.CharField(source='teacher.employee_id', read_only=True)
    marked_by_name = serializers.CharField(source='marked_by.get_full_name', read_only=True)

    class Meta:
        model = TeacherAttendance
        fields = '__all__'
        # marked_by is always set from the logged-in user, never the client.
        read_only_fields = ['marked_by', 'created_at', 'updated_at']

    def validate(self, attrs):
        teacher = attrs.get('teacher') or getattr(self.instance, 'teacher', None)
        date = attrs.get('date') or getattr(self.instance, 'date', None)

        existing = TeacherAttendance.objects.filter(teacher=teacher, date=date)
        if self.instance:
            existing = existing.exclude(pk=self.instance.pk)
        if existing.exists():
            raise serializers.ValidationError(
                'Attendance for this teacher and date has already been recorded.'
            )

        return attrs
