# Generated by Django 6.1 on 2026-08-30 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('father_mobile', models.CharField(blank=True, max_length=15)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('mother_mobile', models.CharField(blank=True, max_length=15)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('guardian_mobile', models.CharField(blank=True, max_length=15)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('current_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('admission_date', models.DateField()),
                ('batch', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('BIRTH_CERT', 'Birth Certificate'), ('TRANSFER_CERT', 'Transfer Certificate'), ('MIGRATION_CERT', 'Migration Certificate'), ('MARKSHEET', 'Marksheet'), ('CHARACTER_CERT', 'Character Certificate'), ('INCOME_CERT', 'Income Certificate'), ('CASTE_CERT', 'Caste Certificate'), ('PASSPORT_PHOTO', 'Passport Photo'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
