# Generated by Django 5.0.6 on 2026-10-02 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
